version: "3.7"
services:
  outside:
    container_name: "outside"
    build: "./outside"
    networks:
        outside_network:
           ipv4_address: 192.168.1.3
  jumphost:
    container_name: "jumphost"
    build: "./jumphost"
    networks:
        outside_network:
           ipv4_address: 192.168.1.5
        inside_network:
           ipv4_address: 192.168.2.5     
    cap_add:
     - NET_ADMIN
  inside_server:
    container_name: "inside_server"
    build: "./inside_server"
    networks:
        inside_network:
           ipv4_address: 192.168.2.50
  inside_client:  
    container_name: "inside_client"
    build: "./inside_client"
    networks:
        inside_network:
           ipv4_address: 192.168.2.110 

networks:
    outside_network:
        ipam:
            config:
              - subnet: 192.168.1.0/24
    inside_network:
        ipam:
             config:
              - subnet: 192.168.2.0/24
